baseurl         = "/"
theme = "novela"
#theme = "ea-theme"
languageCode    = "en-US"
paginate = 12

[social]
twitter= "https://twitter.com/magiceldridge"
github= "https://github.com/eldridgea"
linkedin= "https://www.linkedin.com/in/eldridgea/"
#instagram = "#"
#dribbble = "#"
#youtube = "#"

[taxonomies]
author = "authors"

[permalinks]
  post = '/:year/:month/:day/:title/'
