baseurl = "https://code.naphos.com/proxy/1919/"
theme = "novela"
languageCode = "en-US"
paginate = 12
title = "Eldridge's Blog"

[params]
  [params.social]
    twitter = "https://twitter.com/magiceldridge"
    github = "https://github.com/eldridgea"
    linkedin = "https://www.linkedin.com/in/eldridgea/"

  [params.author]
    name = "Eldridge Alexander"

[taxonomies]
author = "authors"

[permalinks]
  post = '/:year/:month/:day/:title/'
