baseurl         = "/"
theme = "novela"
languageCode    = "en-US"
paginate = 12

[social]
twitter= "https://twitter.com/magiceldridge"
github= "https://github.com/eldridgea"
linkedin= "https://www.linkedin.com/in/eldridgea/"


[taxonomies]
author = "authors"

[permalinks]
  post = '/:year/:month/:day/:title/'
