baseurl         = "/"
theme = "hugo-theme-novela-3"
#theme = "ea-theme"
languageCode    = "en-US"
paginate = 6

[social]
twitter= "https://twitter.com/magiceldridge"
github= "https://github.com/eldridgea"
linkedin= "https://www.linkedin.com/company/forestry.io"
instagram = "#"
dribbble = "#"
youtube = "#"

[taxonomies]
author = "authors"

[permalinks]
  post = '/:year/:month/:day/:title/'
