baseurl = "./proxy/1313"
theme = "novela"
languageCode = "en-US"
paginate = 12
title = "Eldridge's Blog"

[params]
  [params.social]
    twitter = "https://twitter.com/magiceldridge"
    github = "https://github.com/eldridgea"
    linkedin = "https://www.linkedin.com/in/eldridgea/"
    mastodon = "https://infosec.exchange/@eldridge"
    tiktok = "https://www.tiktok.com/@magiceldridge"

  [params.author]
    name = "Eldridge Alexander"


[taxonomies]
author = "authors"

[permalinks]
  post = '/:year/:month/:day/:title/'


[privacy]
  [privacy.youTube]
    disable = false
    privacyEnhanced = false
